//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhorcadoCliente.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AhorcadoCliente.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver.
        /// </summary>
        public static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de nacimiento.
        /// </summary>
        public static string BirthDateRegister {
            get {
                return ResourceManager.GetString("BirthDateRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string CancelCreateMatchButton {
            get {
                return ResourceManager.GetString("CancelCreateMatchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseas cancelar la creacion de la partida? .
        /// </summary>
        public static string CancelCreateMatchMessage {
            get {
                return ResourceManager.GetString("CancelCreateMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar registro.
        /// </summary>
        public static string CancelRegisterButton {
            get {
                return ResourceManager.GetString("CancelRegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorias.
        /// </summary>
        public static string CategoriesCreateMatch {
            get {
                return ResourceManager.GetString("CategoriesCreateMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El retador ha dejado el juego.
        /// </summary>
        public static string ChallengerLeaveMatchMessage {
            get {
                return ResourceManager.GetString("ChallengerLeaveMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmacion.
        /// </summary>
        public static string ConfirmationMessage {
            get {
                return ResourceManager.GetString("ConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear cuenta.
        /// </summary>
        public static string CreateAccountButton {
            get {
                return ResourceManager.GetString("CreateAccountButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear partida.
        /// </summary>
        public static string CreateMatch {
            get {
                return ResourceManager.GetString("CreateMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear partida.
        /// </summary>
        public static string CreateMatchButton {
            get {
                return ResourceManager.GetString("CreateMatchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jugador derrotado.
        /// </summary>
        public static string DataGridColumnChallengerDefeat {
            get {
                return ResourceManager.GetString("DataGridColumnChallengerDefeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de la partida.
        /// </summary>
        public static string DataGridColumnDate {
            get {
                return ResourceManager.GetString("DataGridColumnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        public static string DataGridColumnEmail {
            get {
                return ResourceManager.GetString("DataGridColumnEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unirse.
        /// </summary>
        public static string DataGridColumnJoin {
            get {
                return ResourceManager.GetString("DataGridColumnJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NickName.
        /// </summary>
        public static string DataGridColumnNickName {
            get {
                return ResourceManager.GetString("DataGridColumnNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        public static string EmailLoggin {
            get {
                return ResourceManager.GetString("EmailLoggin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        public static string EmailRegister {
            get {
                return ResourceManager.GetString("EmailRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingles.
        /// </summary>
        public static string EnglishButton {
            get {
                return ResourceManager.GetString("EnglishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingles.
        /// </summary>
        public static string EnglishComboItem {
            get {
                return ResourceManager.GetString("EnglishComboItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrasena y/o email incorrectos!.
        /// </summary>
        public static string ErrorLogginMessage {
            get {
                return ResourceManager.GetString("ErrorLogginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        public static string ExitGameButton {
            get {
                return ResourceManager.GetString("ExitGameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido paterno.
        /// </summary>
        public static string FirstNameRegister {
            get {
                return ResourceManager.GetString("FirstNameRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona el idioma de la palabra.
        /// </summary>
        public static string GameLanguageLabel {
            get {
                return ResourceManager.GetString("GameLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El invitado dejo el juego!.
        /// </summary>
        public static string GuestLeaveMatchMessage {
            get {
                return ResourceManager.GetString("GuestLeaveMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahorcado.
        /// </summary>
        public static string HangmanTittle {
            get {
                return ResourceManager.GetString("HangmanTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor ingresa todos los datos!.
        /// </summary>
        public static string IncompleteLogginMessage {
            get {
                return ResourceManager.GetString("IncompleteLogginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar.
        /// </summary>
        public static string IntroButton {
            get {
                return ResourceManager.GetString("IntroButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Te has unido a la partida!.
        /// </summary>
        public static string JoinGameMessage {
            get {
                return ResourceManager.GetString("JoinGameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al unirse a la partida.
        /// </summary>
        public static string JoinMatchErrorMessage {
            get {
                return ResourceManager.GetString("JoinMatchErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandonar partida.
        /// </summary>
        public static string LeaveMatchButton {
            get {
                return ResourceManager.GetString("LeaveMatchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseas abandonar el juego? .
        /// </summary>
        public static string LeaveMatchConfirmation {
            get {
                return ResourceManager.GetString("LeaveMatchConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partidas disponibles.
        /// </summary>
        public static string LobbyLabel {
            get {
                return ResourceManager.GetString("LobbyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido al juego.
        /// </summary>
        public static string LogginMessage {
            get {
                return ResourceManager.GetString("LogginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicia Sesión.
        /// </summary>
        public static string LoginLabel {
            get {
                return ResourceManager.GetString("LoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar sesion.
        /// </summary>
        public static string LogOutButton {
            get {
                return ResourceManager.GetString("LogOutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseas salir del juego? .
        /// </summary>
        public static string LogOutMessage {
            get {
                return ResourceManager.GetString("LogOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El invitado adivino la palabra, perdiste!.
        /// </summary>
        public static string LosserChallengerMessage {
            get {
                return ResourceManager.GetString("LosserChallengerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perdiste!.
        /// </summary>
        public static string LosserMatchMessage {
            get {
                return ResourceManager.GetString("LosserMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partida creada!.
        /// </summary>
        public static string MatchCreatedMessage {
            get {
                return ResourceManager.GetString("MatchCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historial de partidas.
        /// </summary>
        public static string MatchHistoryButton {
            get {
                return ResourceManager.GetString("MatchHistoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historial de partidas.
        /// </summary>
        public static string MatchHistoryLabel {
            get {
                return ResourceManager.GetString("MatchHistoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has abandonado la partida.
        /// </summary>
        public static string MatchLeaveMessage {
            get {
                return ResourceManager.GetString("MatchLeaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al abandonar la partida.
        /// </summary>
        public static string MatchLeaveMessageError {
            get {
                return ResourceManager.GetString("MatchLeaveMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombres.
        /// </summary>
        public static string NamesRegister {
            get {
                return ResourceManager.GetString("NamesRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        public static string NickNameRegister {
            get {
                return ResourceManager.GetString("NickNameRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar contrasena.
        /// </summary>
        public static string PasswordConfirmationRegister {
            get {
                return ResourceManager.GetString("PasswordConfirmationRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrasena.
        /// </summary>
        public static string PasswordLoggin {
            get {
                return ResourceManager.GetString("PasswordLoggin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrasena.
        /// </summary>
        public static string PasswordRegister {
            get {
                return ResourceManager.GetString("PasswordRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otro jugador se ha unido!.
        /// </summary>
        public static string PlayerJoinedMessage {
            get {
                return ResourceManager.GetString("PlayerJoinedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido materno.
        /// </summary>
        public static string SecondNameRegister {
            get {
                return ResourceManager.GetString("SecondNameRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona la palabra .
        /// </summary>
        public static string SelectWordCreateMatch {
            get {
                return ResourceManager.GetString("SelectWordCreateMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espanol.
        /// </summary>
        public static string SpanishButton {
            get {
                return ResourceManager.GetString("SpanishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espanol.
        /// </summary>
        public static string SpanishComboItem {
            get {
                return ResourceManager.GetString("SpanishComboItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        public static string TelephoneRegister {
            get {
                return ResourceManager.GetString("TelephoneRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juego ahorcado.
        /// </summary>
        public static string Tittle {
            get {
                return ResourceManager.GetString("Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tienes una cuenta? Crea una!.
        /// </summary>
        public static string UserRegisterLabel {
            get {
                return ResourceManager.GetString("UserRegisterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Perfil.
        /// </summary>
        public static string ViewProfileButton {
            get {
                return ResourceManager.GetString("ViewProfileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esperando a otro jugador.
        /// </summary>
        public static string WaitGuestMessage {
            get {
                return ResourceManager.GetString("WaitGuestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El invitado no adivino la palabra, ganaste!.
        /// </summary>
        public static string WinnerMatchMessageChallenger {
            get {
                return ResourceManager.GetString("WinnerMatchMessageChallenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adivinaste la palabra, Ganaste!.
        /// </summary>
        public static string WinnerMatchMessageGuest {
            get {
                return ResourceManager.GetString("WinnerMatchMessageGuest", resourceCulture);
            }
        }
    }
}
