//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhorcadoCliente.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AhorcadoCliente.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de nacimiento.
        /// </summary>
        public static string BirthDateRegister {
            get {
                return ResourceManager.GetString("BirthDateRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string CancelCreateMatchButton {
            get {
                return ResourceManager.GetString("CancelCreateMatchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar registro.
        /// </summary>
        public static string CancelRegisterButton {
            get {
                return ResourceManager.GetString("CancelRegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categorias.
        /// </summary>
        public static string CategoriesCreateMatch {
            get {
                return ResourceManager.GetString("CategoriesCreateMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El retador ha dejado el juego.
        /// </summary>
        public static string ChallengerLeaveMatchMessage {
            get {
                return ResourceManager.GetString("ChallengerLeaveMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear cuenta.
        /// </summary>
        public static string CreateAccountButton {
            get {
                return ResourceManager.GetString("CreateAccountButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear partida.
        /// </summary>
        public static string CreateMatch {
            get {
                return ResourceManager.GetString("CreateMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear partida.
        /// </summary>
        public static string CreateMatchButton {
            get {
                return ResourceManager.GetString("CreateMatchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de la partida.
        /// </summary>
        public static string DataGridColumnDate {
            get {
                return ResourceManager.GetString("DataGridColumnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        public static string DataGridColumnEmail {
            get {
                return ResourceManager.GetString("DataGridColumnEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse.
        /// </summary>
        public static string DataGridColumnJoin {
            get {
                return ResourceManager.GetString("DataGridColumnJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NickName.
        /// </summary>
        public static string DataGridColumnNickName {
            get {
                return ResourceManager.GetString("DataGridColumnNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        public static string EmailLoggin {
            get {
                return ResourceManager.GetString("EmailLoggin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        public static string EmailRegister {
            get {
                return ResourceManager.GetString("EmailRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingles.
        /// </summary>
        public static string EnglishButton {
            get {
                return ResourceManager.GetString("EnglishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingles.
        /// </summary>
        public static string EnglishComboItem {
            get {
                return ResourceManager.GetString("EnglishComboItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrasena y/o email incorrectos!.
        /// </summary>
        public static string ErrorLogginMessage {
            get {
                return ResourceManager.GetString("ErrorLogginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido paterno.
        /// </summary>
        public static string FirstNameRegister {
            get {
                return ResourceManager.GetString("FirstNameRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona el idioma de la palabra.
        /// </summary>
        public static string GameLanguageLabel {
            get {
                return ResourceManager.GetString("GameLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El invitado dejo el juego!.
        /// </summary>
        public static string GuestLeaveMatchMessage {
            get {
                return ResourceManager.GetString("GuestLeaveMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor ingresa todos los datos!.
        /// </summary>
        public static string IncompleteLogginMessage {
            get {
                return ResourceManager.GetString("IncompleteLogginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar.
        /// </summary>
        public static string IntroButton {
            get {
                return ResourceManager.GetString("IntroButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Te has unido a la partida!.
        /// </summary>
        public static string JoinGameMessage {
            get {
                return ResourceManager.GetString("JoinGameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al unirse a la partida.
        /// </summary>
        public static string JoinMatchErrorMessage {
            get {
                return ResourceManager.GetString("JoinMatchErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abandonar partida.
        /// </summary>
        public static string LeaveMatchButton {
            get {
                return ResourceManager.GetString("LeaveMatchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partidas disponibles.
        /// </summary>
        public static string LobbyLabel {
            get {
                return ResourceManager.GetString("LobbyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido al juego.
        /// </summary>
        public static string LogginMessage {
            get {
                return ResourceManager.GetString("LogginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perdiste!.
        /// </summary>
        public static string LosserMatchMessage {
            get {
                return ResourceManager.GetString("LosserMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida creada!.
        /// </summary>
        public static string MatchCreatedMessage {
            get {
                return ResourceManager.GetString("MatchCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has abandonado la partida.
        /// </summary>
        public static string MatchLeaveMessage {
            get {
                return ResourceManager.GetString("MatchLeaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al abandonar la partida.
        /// </summary>
        public static string MatchLeaveMessageError {
            get {
                return ResourceManager.GetString("MatchLeaveMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres.
        /// </summary>
        public static string NamesRegister {
            get {
                return ResourceManager.GetString("NamesRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nickname.
        /// </summary>
        public static string NickNameRegister {
            get {
                return ResourceManager.GetString("NickNameRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contrasena.
        /// </summary>
        public static string PasswordConfirmationRegister {
            get {
                return ResourceManager.GetString("PasswordConfirmationRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrasena.
        /// </summary>
        public static string PasswordLoggin {
            get {
                return ResourceManager.GetString("PasswordLoggin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrasena.
        /// </summary>
        public static string PasswordRegister {
            get {
                return ResourceManager.GetString("PasswordRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otro jugador se ha unido!.
        /// </summary>
        public static string PlayerJoinedMessage {
            get {
                return ResourceManager.GetString("PlayerJoinedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido materno.
        /// </summary>
        public static string SecondNameRegister {
            get {
                return ResourceManager.GetString("SecondNameRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona la palabra .
        /// </summary>
        public static string SelectWordCreateMatch {
            get {
                return ResourceManager.GetString("SelectWordCreateMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espanol.
        /// </summary>
        public static string SpanishButton {
            get {
                return ResourceManager.GetString("SpanishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espanol.
        /// </summary>
        public static string SpanishComboItem {
            get {
                return ResourceManager.GetString("SpanishComboItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telefono.
        /// </summary>
        public static string TelephoneRegister {
            get {
                return ResourceManager.GetString("TelephoneRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Juego ahorcado.
        /// </summary>
        public static string Tittle {
            get {
                return ResourceManager.GetString("Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes una cuenta? Crea una!.
        /// </summary>
        public static string UserRegisterLabel {
            get {
                return ResourceManager.GetString("UserRegisterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esperando a otro jugador.
        /// </summary>
        public static string WaitGuestMessage {
            get {
                return ResourceManager.GetString("WaitGuestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El invitado no adivino la palabra, ganaste!.
        /// </summary>
        public static string WinnerMatchMessageChallenger {
            get {
                return ResourceManager.GetString("WinnerMatchMessageChallenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adivinaste la palabra, Ganaste!.
        /// </summary>
        public static string WinnerMatchMessageGuest {
            get {
                return ResourceManager.GetString("WinnerMatchMessageGuest", resourceCulture);
            }
        }
    }
}
