//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhorcadoCliente.ServiceReference3 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/AhorcadoServicios.Model.POCO")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string categoria_espanolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string categoria_inglesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_categoriaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string categoria_espanol {
            get {
                return this.categoria_espanolField;
            }
            set {
                if ((object.ReferenceEquals(this.categoria_espanolField, value) != true)) {
                    this.categoria_espanolField = value;
                    this.RaisePropertyChanged("categoria_espanol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string categoria_ingles {
            get {
                return this.categoria_inglesField;
            }
            set {
                if ((object.ReferenceEquals(this.categoria_inglesField, value) != true)) {
                    this.categoria_inglesField = value;
                    this.RaisePropertyChanged("categoria_ingles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_categoria {
            get {
                return this.id_categoriaField;
            }
            set {
                if ((this.id_categoriaField.Equals(value) != true)) {
                    this.id_categoriaField = value;
                    this.RaisePropertyChanged("id_categoria");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Word", Namespace="http://schemas.datacontract.org/2004/07/AhorcadoServicios.Model.POCO")]
    [System.SerializableAttribute()]
    public partial class Word : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_categoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_palabraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string palabra_espanolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string palabra_inglesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pista_espanolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pista_inglesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_categoria {
            get {
                return this.id_categoriaField;
            }
            set {
                if ((this.id_categoriaField.Equals(value) != true)) {
                    this.id_categoriaField = value;
                    this.RaisePropertyChanged("id_categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_palabra {
            get {
                return this.id_palabraField;
            }
            set {
                if ((this.id_palabraField.Equals(value) != true)) {
                    this.id_palabraField = value;
                    this.RaisePropertyChanged("id_palabra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string palabra_espanol {
            get {
                return this.palabra_espanolField;
            }
            set {
                if ((object.ReferenceEquals(this.palabra_espanolField, value) != true)) {
                    this.palabra_espanolField = value;
                    this.RaisePropertyChanged("palabra_espanol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string palabra_ingles {
            get {
                return this.palabra_inglesField;
            }
            set {
                if ((object.ReferenceEquals(this.palabra_inglesField, value) != true)) {
                    this.palabra_inglesField = value;
                    this.RaisePropertyChanged("palabra_ingles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pista_espanol {
            get {
                return this.pista_espanolField;
            }
            set {
                if ((object.ReferenceEquals(this.pista_espanolField, value) != true)) {
                    this.pista_espanolField = value;
                    this.RaisePropertyChanged("pista_espanol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pista_ingles {
            get {
                return this.pista_inglesField;
            }
            set {
                if ((object.ReferenceEquals(this.pista_inglesField, value) != true)) {
                    this.pista_inglesField = value;
                    this.RaisePropertyChanged("pista_ingles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.IWordService")]
    public interface IWordService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordService/GetCategories", ReplyAction="http://tempuri.org/IWordService/GetCategoriesResponse")]
        AhorcadoCliente.ServiceReference3.Category[] GetCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordService/GetCategories", ReplyAction="http://tempuri.org/IWordService/GetCategoriesResponse")]
        System.Threading.Tasks.Task<AhorcadoCliente.ServiceReference3.Category[]> GetCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordService/GetWordsPerCategory", ReplyAction="http://tempuri.org/IWordService/GetWordsPerCategoryResponse")]
        AhorcadoCliente.ServiceReference3.Word[] GetWordsPerCategory(int category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordService/GetWordsPerCategory", ReplyAction="http://tempuri.org/IWordService/GetWordsPerCategoryResponse")]
        System.Threading.Tasks.Task<AhorcadoCliente.ServiceReference3.Word[]> GetWordsPerCategoryAsync(int category);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWordServiceChannel : AhorcadoCliente.ServiceReference3.IWordService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WordServiceClient : System.ServiceModel.ClientBase<AhorcadoCliente.ServiceReference3.IWordService>, AhorcadoCliente.ServiceReference3.IWordService {
        
        public WordServiceClient() {
        }
        
        public WordServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WordServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AhorcadoCliente.ServiceReference3.Category[] GetCategories() {
            return base.Channel.GetCategories();
        }
        
        public System.Threading.Tasks.Task<AhorcadoCliente.ServiceReference3.Category[]> GetCategoriesAsync() {
            return base.Channel.GetCategoriesAsync();
        }
        
        public AhorcadoCliente.ServiceReference3.Word[] GetWordsPerCategory(int category) {
            return base.Channel.GetWordsPerCategory(category);
        }
        
        public System.Threading.Tasks.Task<AhorcadoCliente.ServiceReference3.Word[]> GetWordsPerCategoryAsync(int category) {
            return base.Channel.GetWordsPerCategoryAsync(category);
        }
    }
}
