//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhorcadoCliente.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Match", Namespace="http://schemas.datacontract.org/2004/07/AhorcadoServicios.Model.POCO")]
    [System.SerializableAttribute()]
    public partial class Match : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correo_creadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estado_partidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_partidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_creadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> id_ganadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_palabraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_partidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> id_retadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intentos_restantesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<char> letra_seleccionadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nickname_creadorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correo_creador {
            get {
                return this.correo_creadorField;
            }
            set {
                if ((object.ReferenceEquals(this.correo_creadorField, value) != true)) {
                    this.correo_creadorField = value;
                    this.RaisePropertyChanged("correo_creador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado_partida {
            get {
                return this.estado_partidaField;
            }
            set {
                if ((this.estado_partidaField.Equals(value) != true)) {
                    this.estado_partidaField = value;
                    this.RaisePropertyChanged("estado_partida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fecha_partida {
            get {
                return this.fecha_partidaField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_partidaField, value) != true)) {
                    this.fecha_partidaField = value;
                    this.RaisePropertyChanged("fecha_partida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_creador {
            get {
                return this.id_creadorField;
            }
            set {
                if ((this.id_creadorField.Equals(value) != true)) {
                    this.id_creadorField = value;
                    this.RaisePropertyChanged("id_creador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_ganador {
            get {
                return this.id_ganadorField;
            }
            set {
                if ((this.id_ganadorField.Equals(value) != true)) {
                    this.id_ganadorField = value;
                    this.RaisePropertyChanged("id_ganador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_palabra {
            get {
                return this.id_palabraField;
            }
            set {
                if ((this.id_palabraField.Equals(value) != true)) {
                    this.id_palabraField = value;
                    this.RaisePropertyChanged("id_palabra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_partida {
            get {
                return this.id_partidaField;
            }
            set {
                if ((this.id_partidaField.Equals(value) != true)) {
                    this.id_partidaField = value;
                    this.RaisePropertyChanged("id_partida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_retador {
            get {
                return this.id_retadorField;
            }
            set {
                if ((this.id_retadorField.Equals(value) != true)) {
                    this.id_retadorField = value;
                    this.RaisePropertyChanged("id_retador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intentos_restantes {
            get {
                return this.intentos_restantesField;
            }
            set {
                if ((this.intentos_restantesField.Equals(value) != true)) {
                    this.intentos_restantesField = value;
                    this.RaisePropertyChanged("intentos_restantes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<char> letra_seleccionada {
            get {
                return this.letra_seleccionadaField;
            }
            set {
                if ((this.letra_seleccionadaField.Equals(value) != true)) {
                    this.letra_seleccionadaField = value;
                    this.RaisePropertyChanged("letra_seleccionada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nickname_creador {
            get {
                return this.nickname_creadorField;
            }
            set {
                if ((object.ReferenceEquals(this.nickname_creadorField, value) != true)) {
                    this.nickname_creadorField = value;
                    this.RaisePropertyChanged("nickname_creador");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IGameServices")]
    public interface IGameServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/createMatch", ReplyAction="http://tempuri.org/IGameServices/createMatchResponse")]
        bool createMatch([System.ServiceModel.MessageParameterAttribute(Name="createMatch")] AhorcadoCliente.ServiceReference2.Match createMatch1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/createMatch", ReplyAction="http://tempuri.org/IGameServices/createMatchResponse")]
        System.Threading.Tasks.Task<bool> createMatchAsync(AhorcadoCliente.ServiceReference2.Match createMatch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/getMatchList", ReplyAction="http://tempuri.org/IGameServices/getMatchListResponse")]
        AhorcadoCliente.ServiceReference2.Match[] getMatchList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/getMatchList", ReplyAction="http://tempuri.org/IGameServices/getMatchListResponse")]
        System.Threading.Tasks.Task<AhorcadoCliente.ServiceReference2.Match[]> getMatchListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameServicesChannel : AhorcadoCliente.ServiceReference2.IGameServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameServicesClient : System.ServiceModel.ClientBase<AhorcadoCliente.ServiceReference2.IGameServices>, AhorcadoCliente.ServiceReference2.IGameServices {
        
        public GameServicesClient() {
        }
        
        public GameServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GameServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool createMatch(AhorcadoCliente.ServiceReference2.Match createMatch1) {
            return base.Channel.createMatch(createMatch1);
        }
        
        public System.Threading.Tasks.Task<bool> createMatchAsync(AhorcadoCliente.ServiceReference2.Match createMatch) {
            return base.Channel.createMatchAsync(createMatch);
        }
        
        public AhorcadoCliente.ServiceReference2.Match[] getMatchList() {
            return base.Channel.getMatchList();
        }
        
        public System.Threading.Tasks.Task<AhorcadoCliente.ServiceReference2.Match[]> getMatchListAsync() {
            return base.Channel.getMatchListAsync();
        }
    }
}
